# coding: utf-8
lib = File.expand_path('../lib', __FILE__)
$LOAD_PATH.unshift(lib) unless $LOAD_PATH.include?(lib)
require 'xcprofiler/version'

Gem::Specification.new do |spec|
  spec.name          = "xcprofiler"
  spec.version       = Xcprofiler::VERSION
  spec.authors       = ["giginet"]
  spec.email         = ["giginet.net@gmail.com"]

  spec.summary       = %q{CLI to profile compilation time of Swift projects}
  spec.description   = %q{xcprofiler parses activity logs generated by Xcode and reports build time of Swift projects}
  spec.homepage      = 'https://github.com/giginet/xcprofiler'

  spec.files         = `git ls-files -z`.split("\x0").reject { |f| f.match(%r{^(test|spec|features)/}) }
  spec.executables   = spec.files.grep(%r{^bin/}) { |f| File.basename(f) }
  spec.require_paths = ["lib"]

  spec.add_development_dependency "bundler", "~> 1.6"
  spec.add_development_dependency "rake", "~> 10.0"
  spec.add_development_dependency "rspec"
  spec.add_development_dependency "coveralls"

  spec.add_dependency 'terminal-table'
  spec.add_dependency 'colored2'
end
